language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# Temporarily, until proper python 3.7 support is in Travis
matrix:
    include:
        - python: 3.7
          dist: xenial
cache: pip
install:
  - ./waf configure
script:
  - ./waf build --run_tests
