name: Waf Python Tests
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # 3 AM CET
  push:
  pull_request:
jobs:
  waf:
    strategy:
      fail-fast: false
      matrix:
        os: [Windows, Linux]
        include:
          - os: Windows
            PYTHON: python
          - os: Linux
            PYTHON: python3
    runs-on: [self-hosted, "${{ matrix.os }}"]
    name: ${{ matrix.os }} Waf
    env:
      python: python3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: ${{ matrix.PYTHON }} waf configure
      - name: Build
        run: ${{ matrix.PYTHON }} waf
      - name: Test
        run: ${{ matrix.PYTHON }} waf --run_tests
