jobs:
  waf-linux:
    container:
      image: ghcr.io/steinwurf/twine:latest
      options: --user 0:0
      volumes:
      - /home/buildbot/.ssh:/root/.ssh
    name: Linux Waf
    runs-on:
    - self-hosted
    - docker
    - builder
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure
      run: python3 waf configure
    - name: Build
      run: python3 waf
    - name: Test
      run: python3 waf --run_tests -vv
  waf-macos:
    name: macOS Waf
    runs-on:
    - self-hosted
    - macOS
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure
      run: python3 waf configure
    - name: Build
      run: python3 waf
    - name: Test
      run: python3 waf --run_tests -vv
  waf-windows:
    name: Windows Waf
    runs-on:
    - self-hosted
    - Windows
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure
      run: python waf configure
    - name: Build
      run: python waf
    - name: Test
      run: python waf --run_tests -vv
name: Waf Python Tests
'on':
  pull_request: null
  push:
    branches:
    - master
  schedule:
  - cron: 0 1 * * *
  workflow_dispatch: null
