name: Waf Python Tests
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # 3 AM CET
  push:
  pull_request:
jobs:
  waf-windows:
    runs-on: [self-hosted, Windows]
    name: Windows Waf
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: python waf configure
      - name: Build
        run: python waf
      - name: Test
        run: python waf --run_tests -vv
  waf-linux:
    runs-on: [self-hosted, docker, builder]
    name: Linux Waf
    container:
      image: ghcr.io/steinwurf/twine:latest
      options: --user 0:0
      volumes:
        - /home/buildbot/.ssh:/root/.ssh
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: python3 waf configure
      - name: Build
        run: python3 waf
      - name: Test
        run: python3 waf --run_tests -vv
  waf-macos:
    runs-on: [self-hosted, macOS]
    name: macOS Waf
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: python3 waf configure
      - name: Build
        run: python3 waf
      - name: Test
        run: python3 waf --run_tests -vv

# Cancel previous in-progress when pushing: https://stackoverflow.com/a/72408109
concurrency:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

# Cancel previous in-progress when pushing: https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
